# Generated by Django 2.0.7 on 2019-03-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='cardNumber',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='email',
        ),
    ]
